### ISSUE TITLE
Multiple AGI Call

### ISSUE THREAD

**Issue by chandrakant2511** [marcelog/FastPAGI#2]
Hello,

Is this possible to call multiple FastPAGI. Like I have 15 FastAGI, which I have to call.
So, how it could be possible?

[application]
bootstrap=/var/lib/asterisk/agi-bin/FastPAGI-master/PAGI/docs/examples/quickstart/MyPAGIApplication.php
class=MyPAGIApplication
bootstrap=/var/lib/asterisk/agi-bin/FastPAGI-master/PAGI/docs/examples/quickstart/MyPAGIApplication1.php
class=MyPAGIApplication1
bootstrap=/var/lib/asterisk/agi-bin/FastPAGI-master/PAGI/docs/examples/quickstart/MyPAGIApplication2.php
class=MyPAGIApplication2
log4php=/tmp/log4php.properties

Thanks

**Comment by marcelog** [comment]
No, but you could "route" to the corresponding application in your main application, or even in your fastagi.php script. I'll close this now, since this is not an issue.
